apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/ecommerce
    targetRevision: main
    path: k8s/gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-stack
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/ecommerce
    targetRevision: main
    path: k8s/platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-stack
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/ecommerce
    targetRevision: main
    path: k8s/istio
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-stack
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/your-org/ecommerce
    targetRevision: main
    path: k8s/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
