apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-mongodb
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.6.12
    helm:
      releaseName: mongodb
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
