apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: apps-notifications
  labels:
    app: notifications-api
data:
  SERVICE_NAME: notifications-api
  SERVICE_ENV: k8s
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observability.svc.cluster.local:4317
  ASPNETCORE_URLS: http://0.0.0.0:8080
  KAFKA_BOOTSTRAP_SERVERS: kafka.platform.svc.cluster.local:9092
  KAFKA_TOPIC: orders.events
  KAFKA_GROUP_ID: notifications-api
  RABBITMQ_HOST: rabbitmq.platform.svc.cluster.local
  RABBITMQ_USERNAME: ecommerce
  RABBITMQ_QUEUE: notifications.send
---
apiVersion: v1
kind: Secret
metadata:
  name: notifications-api-secrets
  namespace: apps-notifications
  labels:
    app: notifications-api
stringData:
  RABBITMQ_PASSWORD: ecommerce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: apps-notifications
  labels:
    app: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: localhost:5000/ecommerce-notifications-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-api-config
            - secretRef:
                name: notifications-api-secrets
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-api
  namespace: apps-notifications
  labels:
    app: notifications-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: notifications-api
