version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: ecommerce-jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REGISTRY: "localhost:5000"
    networks:
      - jenkins-net

  registry:
    image: registry:2
    container_name: ecommerce-local-registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - jenkins-net

networks:
  jenkins-net:
    name: ecommerce-jenkins-net

volumes:
  jenkins_home:
  registry_data:
