apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Application workloads for the e-commerce lab.
  destinations:
    - namespace: apps
      server: https://kubernetes.default.svc
    - namespace: apps-notifications
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/your-org/ecommerce
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
